name: Build Pull Request
on: pull_request
permissions:
  contents: read
jobs:
  build:
    envs:
      NX_VERBOSE_LOGGING: true
      NX_PERF_LOGGING: true
    name: Build Pull Request
    if: ${{ github.repository == 'spring-projects/spring-boot' }}
    runs-on: ${{ vars.UBUNTU_MEDIUM || 'ubuntu-latest' }}
    steps:
      - name: Java 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: List directories
        run: ls -laR .nx

      # - name: Show projects (cold)
      #   run: npx nx show projects
      #
      # - name: Show projects (warm)
      #   run: npx nx show projects
      #
      - name: Run to cache
        run: npx nx build spring-boot-starter

      - name: Build
        id: build
        uses: ./.github/actions/build
      - name: Print JVM Thread Dumps When Cancelled
        if: cancelled()
        uses: ./.github/actions/print-jvm-thread-dumps
      - name: Upload Build Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: '**/build/reports/'
